name: "Publish Documentation to NIST Pages"

concurrency:
   group: ${{ github.workflow }}
   cancel-in-progress: false

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # - uses: martintb/Docs4NIST@themedir-bug
      - uses: usnistgov/Docs4NIST@0.7
        with:
          docs-folder: docs/
          # pip-requirements: "requirements_sphinx820.txt"
          conda-environment: "docs.yml"
          # pip-requirements: "requirements.txt"

